/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/sectors': typeof SectorsRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sectors': typeof SectorsRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/sectors': typeof SectorsRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/companies'
    | '/sectors'
    | '/companies/$slug'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/sectors' | '/companies/$slug' | '/companies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/companies'
    | '/sectors'
    | '/companies/$slug'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  SectorsRoute: typeof SectorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesSlugRoute: CompaniesSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  SectorsRoute: SectorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
